name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  fetch:
    runs-on: self-hosted
    steps:
      - name: Pull changes
        run: |
          cd ~/media/docker/cosmos
          git stash --include-untracked
          git reset --hard
          git clean -fd
          ssh-agent bash -c 'ssh-add ~/.ssh/gh_deploy; git pull'
  build:
    runs-on: self-hosted
    steps:
      - name: Install packages
        run: |
          cd ~/media/docker/cosmos
          yarn install
  deploy:
    runs-on: self-hosted
    steps:
      - name: Recreate container
        run: |
          cd ~/media/docker
          docker-compose up -d --force-recreate cosmos
